name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create docs directory if not exists
        run: mkdir -p docs

      - name: Build and deploy
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: '.'
          destination: './docs/_site'
